### ISSUE TITLE
Peak/goto macro definition from within a macro

### ISSUE THREAD

**Issue by Simnbf** [eclipse/che-che4z-lsp-for-hlasm#30] opened 2020-04-17 11:48 UTC
The peak/goto definition feature for expanding macros is great. Is it possible to add a feature to expand a macro included in another macro?

I can't really give a screenshot example as my company blocks github, but we have alot of cases with macros within macros.

**Comment by michalbali256** [comment] 2020-04-17 14:23
Just to be sure: is this issue about:
1. a macro *definition* within a macro as in:
```
   MACRO
   OUTERMAC
   
   MACRO
   INNERMAC
   MEND

   MEND
   
   OUTERMAC
   INNERMAC   <- Go to definition on this INNERMAC does not work
```
2. or a macro *call* within a macro as in:
```
   MACRO
   MAC
   MEND

   MACRO
   MAC2

   MAC   <- Go to definition on this MAC does not work

   MEND

   MAC2
```

**Comment by Simnbf** [comment] 2020-04-17 14:49
A macro call within a macro, your second example.

**Comment by marcel1hruska** [comment] 2020-05-02 16:45
Hi,

This might seem slightly complicated but it actually works as intended.

If you open an open code file with a macro inside, the macro is parsed within the context of the open code. This means that our processor does the dependency resolution also for the contents of the macro. Therefore, if you open the macro after the open code, the `go to definition` should work also for the inner macros.

But, if you open only the macro (open code is closed in the editor), it is parsed within its own context. In this case, the macro cannot be completely processed as the code generated by it may widely depend on its outside usage. Generally, many features are opted when the macros are being parsed without the open code, including `go to definition` for any inner macros.

I hope it makes sense this way. One possible solution for this problem would be an interactive menu where the user can see and select the context for which the macro is to be parsed. But that is not feasible in the near future.

Marcel

**Comment by marcel1hruska** [comment] 2020-05-02 17:56
Let us know if it works for you as I described above. We would much appreciate any feedback/suggestions on how to improve this issue.

**Comment by marcel1hruska** [comment] 2020-07-01 14:13
As there is no longer any activity here, I'm closing the issue. In case you'd like to suggest some improvement, feel free to reopen it.

**Closed** 2020-07-01 14:13 UTC
Labels: enhancement
